import * as fs from 'node:fs';
import * as path from 'node:path';
import { createHash } from 'node:crypto';

/**
 * Per-workspace agent instructions, written on `/api/config/apply` (SCRUM-479).
 *
 * `AGENTS.md` (agents.md open format) is the canonical instruction file we deploy, so a workspace
 * is portable across every engine that reads it natively — Codex, Amp, Jules, Cursor — instead of
 * being Claude-Code-only. `CLAUDE.md` stays on disk as a two-line `@AGENTS.md` import: Claude Code
 * does not read AGENTS.md itself, and an import (rather than a second copy of the text) is what
 * keeps an agent that reads BOTH files from loading the instructions twice.
 *
 * The portal still stores and ships the text in the `claude_md` field — this module decides only
 * which files that text lands in on the agent's disk.
 */

/** Sidecar that marks AGENTS.md as ours. Mirrors `.sb-skill-sha` in skills.ts, same purpose. */
export const OWNERSHIP_MARKER = '.sb-instructions-sha';

/** First line of the `CLAUDE.md` we generate — tells a human reading it where the real file is. */
export const CLAUDE_POINTER_MARKER = '<!-- Generated by SideButton. Canonical instructions: AGENTS.md — edit that file. -->';

/** The generated `CLAUDE.md`: marker + a Claude Code file import of the canonical file. */
export const CLAUDE_POINTER = `${CLAUDE_POINTER_MARKER}\n@AGENTS.md\n`;

/** One written (or deliberately untouched) file, in the shape `/api/config/apply` reports. */
export interface InstructionWrite {
  path: string;
  ok: boolean;
  error?: string;
  /** Set when the file was intentionally left alone; `ok` stays true — a skip is not a failure. */
  skipped?: string;
}

function readIfPresent(filePath: string): string | null {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    // ENOENT (or any read failure) → treat as absent; the write below reports a real error.
    return null;
  }
}

/**
 * Write one file, reporting the outcome instead of throwing.
 *
 * Every write is independent: a failure on one must still leave the other's result in the
 * response, or the operator sees a single opaque error keyed on the entry path and cannot tell
 * which half of the pair actually landed.
 */
function writeFile(filePath: string, content: string): InstructionWrite {
  try {
    fs.writeFileSync(filePath, content, 'utf8');
    return { path: filePath, ok: true };
  } catch (err: any) {
    return { path: filePath, ok: false, error: err?.message ?? String(err) };
  }
}

/**
 * Write the workspace's instruction text, canonically to `AGENTS.md` plus a pointer `CLAUDE.md`.
 *
 * Never clobbers an `AGENTS.md` a human wrote. Ownership is recorded out-of-band, in the
 * `.sb-instructions-sha` sidecar we drop next to the file — the same trick `skills.ts` uses to tell
 * SB-managed skill directories from user-owned ones.
 *
 * Ownership deliberately does NOT depend on `CLAUDE.md`. That file is documented as ours to
 * overwrite and agents are actively invited to edit it, so anything that rewrites it — a `/init`
 * run, a fleet runbook's `cp … CLAUDE.md`, an operator following our own "edit AGENTS.md, not
 * CLAUDE.md" guidance — would erase the only proof we had. The next apply would then read our own
 * AGENTS.md as hand-authored, divert the payload back into CLAUDE.md, and leave AGENTS.md frozen
 * at its last revision *permanently*: self-reinforcing, invisible in the portal, and leaving
 * exactly the engines this ticket exists to serve (Codex, Amp, Cursor) on stale instructions. The
 * sidecar is not user-facing content, so nothing has a reason to rewrite it.
 *
 * Nor does ownership depend on CLAUDE.md's *contents*, which are operator-supplied: instruction
 * text beginning with our marker line would otherwise forge the proof and destroy a genuinely
 * hand-authored AGENTS.md on the following apply.
 *
 * A hand-authored file therefore means: AGENTS.md exists, has content, and no sidecar of ours sits
 * beside it. Then we leave it and fall back to the pre-SCRUM-479 behaviour — full text into
 * CLAUDE.md — so the workspace still receives its portal instructions either way.
 *
 * CLAUDE.md itself carries no such guard: config-apply has always overwritten it unconditionally
 * and the portal has always been its source of truth.
 */
export function writeWorkspaceInstructions(dir: string, content: string): InstructionWrite[] {
  const agentsPath = path.join(dir, 'AGENTS.md');
  const claudePath = path.join(dir, 'CLAUDE.md');
  const markerPath = path.join(dir, OWNERSHIP_MARKER);

  const existingAgents = readIfPresent(agentsPath);
  const owned =
    // Nothing there, or nothing *in* there — an empty file protects no one's work.
    existingAgents === null
    || existingAgents.trim() === ''
    // We wrote this file on an earlier apply.
    || fs.existsSync(markerPath)
    // Already exactly the text we are about to write: adopting it changes no bytes.
    || existingAgents === content;

  if (!owned) {
    return [
      { path: agentsPath, ok: true, skipped: 'hand-authored AGENTS.md left untouched' },
      writeFile(claudePath, content),
    ];
  }

  const agents = writeFile(agentsPath, content);
  // Whether the TEXT reached AGENTS.md — distinct from `agents.ok`, which also goes false when the
  // file landed but the sidecar did not. Only the former decides what CLAUDE.md may contain.
  const textLanded = agents.ok;
  if (agents.ok) {
    // A workspace that takes the content but rejects the sidecar would silently lose ownership on
    // the next apply, so surface that on the AGENTS.md result rather than swallowing it.
    const marker = writeFile(markerPath, `${createHash('sha256').update(content).digest('hex')}\n`);
    if (!marker.ok) {
      agents.ok = false;
      agents.error = `AGENTS.md written but ownership marker failed: ${marker.error}`;
    }
  }

  // The pointer is only safe once AGENTS.md actually holds the text. If that write failed
  // (unwritable path, ENOSPC, a dangling symlink), a `@AGENTS.md` import would resolve to a missing
  // or stale file and the workspace would be left with NO usable instructions — while the previous
  // CLAUDE.md, which did work, got overwritten. Degrade to the pre-SCRUM-479 layout instead: full
  // text into CLAUDE.md, same fallback the hand-authored branch above uses.
  return [agents, writeFile(claudePath, textLanded ? CLAUDE_POINTER : content)];
}
