import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  writeWorkspaceInstructions,
  CLAUDE_POINTER,
  CLAUDE_POINTER_MARKER,
  OWNERSHIP_MARKER,
} from './workspace-instructions.js';

// SCRUM-479: config-apply deploys the instruction text as AGENTS.md (canonical, engine-agnostic)
// and leaves CLAUDE.md as an `@AGENTS.md` import. These tests pin the two things that can bite:
// a hand-authored AGENTS.md must survive, and an existing workspace must keep receiving updates.
describe('writeWorkspaceInstructions', () => {
  let ws: string;
  const BODY = '# Workspace rules\nBe excellent.\n';
  const read = (name: string) => fs.readFileSync(path.join(ws, name), 'utf8');
  const exists = (name: string) => fs.existsSync(path.join(ws, name));

  beforeEach(() => {
    ws = fs.mkdtempSync(path.join(os.tmpdir(), 'sb-instructions-'));
  });

  afterEach(() => {
    fs.rmSync(ws, { recursive: true, force: true });
  });

  it('writes AGENTS.md with the text and CLAUDE.md as an @AGENTS.md import', () => {
    const results = writeWorkspaceInstructions(ws, BODY);

    expect(read('AGENTS.md')).toBe(BODY);
    expect(read('CLAUDE.md')).toBe(CLAUDE_POINTER);
    // The pointer imports rather than duplicates: an agent reading both files loads the text once.
    expect(read('CLAUDE.md')).toContain('@AGENTS.md');
    expect(read('CLAUDE.md')).not.toContain('Be excellent');
    expect(results.map((r) => [path.basename(r.path), r.ok])).toEqual([
      ['AGENTS.md', true],
      ['CLAUDE.md', true],
    ]);
    expect(results.some((r) => r.skipped)).toBe(false);
  });

  it('re-applying updated text overwrites both files (workspace already converted)', () => {
    writeWorkspaceInstructions(ws, BODY);
    writeWorkspaceInstructions(ws, '# New rules\n');

    expect(read('AGENTS.md')).toBe('# New rules\n');
    expect(read('CLAUDE.md')).toBe(CLAUDE_POINTER);
  });

  it('keeps updating a workspace whose AGENTS.md we own even after its text changed', () => {
    // Ownership is the sidecar, not the AGENTS.md content — otherwise the second apply would
    // mistake our own file for a hand-authored one and stop delivering.
    writeWorkspaceInstructions(ws, BODY);
    fs.writeFileSync(path.join(ws, 'AGENTS.md'), '# Drifted on disk\n', 'utf8');

    const results = writeWorkspaceInstructions(ws, '# Third revision\n');

    expect(read('AGENTS.md')).toBe('# Third revision\n');
    expect(results.some((r) => r.skipped)).toBe(false);
  });

  it('keeps ownership when CLAUDE.md is rewritten without the pointer', () => {
    // The regression this sidecar exists for. CLAUDE.md is ours to overwrite and agents are told
    // to edit it, so `/init`, a runbook's `cp … CLAUDE.md`, or an operator can wipe the marker.
    // When ownership hung off that file, the next apply read our own AGENTS.md as hand-authored
    // and froze it at v1 forever while CLAUDE.md kept receiving updates — split-brain, silent.
    writeWorkspaceInstructions(ws, '# v1\n');
    fs.writeFileSync(path.join(ws, 'CLAUDE.md'), '# Regenerated by /init\n', 'utf8');

    const results = writeWorkspaceInstructions(ws, '# v2\n');

    expect(read('AGENTS.md')).toBe('# v2\n');
    expect(read('CLAUDE.md')).toBe(CLAUDE_POINTER);
    expect(results.some((r) => r.skipped)).toBe(false);
  });

  it('survives CLAUDE.md being deleted outright', () => {
    writeWorkspaceInstructions(ws, '# v1\n');
    fs.rmSync(path.join(ws, 'CLAUDE.md'));

    writeWorkspaceInstructions(ws, '# v2\n');

    expect(read('AGENTS.md')).toBe('# v2\n');
    expect(read('CLAUDE.md')).toBe(CLAUDE_POINTER);
  });

  it('never clobbers a hand-authored AGENTS.md — falls back to writing CLAUDE.md', () => {
    const handAuthored = '# Repo conventions\nRun pnpm test before pushing.\n';
    fs.writeFileSync(path.join(ws, 'AGENTS.md'), handAuthored, 'utf8');

    const results = writeWorkspaceInstructions(ws, BODY);

    expect(read('AGENTS.md')).toBe(handAuthored);
    // Legacy behaviour: the workspace still gets its portal instructions, in CLAUDE.md.
    expect(read('CLAUDE.md')).toBe(BODY);
    expect(exists(OWNERSHIP_MARKER)).toBe(false);
    const agents = results.find((r) => r.path.endsWith('AGENTS.md'))!;
    expect(agents.ok).toBe(true);
    expect(agents.skipped).toMatch(/hand-authored/);
  });

  it('keeps refusing a hand-authored AGENTS.md on every later apply', () => {
    const handAuthored = '# Repo conventions\n';
    fs.writeFileSync(path.join(ws, 'AGENTS.md'), handAuthored, 'utf8');

    writeWorkspaceInstructions(ws, BODY);
    const results = writeWorkspaceInstructions(ws, '# Newer portal text\n');

    expect(read('AGENTS.md')).toBe(handAuthored);
    expect(read('CLAUDE.md')).toBe('# Newer portal text\n');
    expect(results.some((r) => r.skipped)).toBe(true);
  });

  it('cannot be tricked into ownership by instruction text that starts with the marker', () => {
    // The fallback path writes operator-supplied text into CLAUDE.md. When ownership was proven by
    // a `startsWith(marker)` check on that file, text beginning with the marker line forged the
    // proof and the next apply destroyed the human's AGENTS.md.
    const handAuthored = '# HAND AUTHORED — do not touch\n';
    fs.writeFileSync(path.join(ws, 'AGENTS.md'), handAuthored, 'utf8');
    const forged = `${CLAUDE_POINTER_MARKER}\n# smuggled instructions\n`;

    writeWorkspaceInstructions(ws, forged);
    writeWorkspaceInstructions(ws, '# real instructions\n');

    expect(read('AGENTS.md')).toBe(handAuthored);
  });

  it('adopts an AGENTS.md that already holds exactly the applied text', () => {
    fs.writeFileSync(path.join(ws, 'AGENTS.md'), BODY, 'utf8');

    const results = writeWorkspaceInstructions(ws, BODY);

    expect(read('AGENTS.md')).toBe(BODY);
    expect(read('CLAUDE.md')).toBe(CLAUDE_POINTER);
    expect(results.some((r) => r.skipped)).toBe(false);
  });

  it('adopts an empty AGENTS.md — a stray touch protects nothing', () => {
    fs.writeFileSync(path.join(ws, 'AGENTS.md'), '   \n', 'utf8');

    const results = writeWorkspaceInstructions(ws, BODY);

    expect(read('AGENTS.md')).toBe(BODY);
    expect(results.some((r) => r.skipped)).toBe(false);
  });

  it('converts a legacy workspace: full-text CLAUDE.md becomes the pointer', () => {
    fs.writeFileSync(path.join(ws, 'CLAUDE.md'), '# Older deployed instructions\n', 'utf8');

    writeWorkspaceInstructions(ws, BODY);

    expect(read('AGENTS.md')).toBe(BODY);
    expect(read('CLAUDE.md')).toBe(CLAUDE_POINTER);
  });

  it('writes the empty pair without error (empty instructions are a valid choice)', () => {
    const results = writeWorkspaceInstructions(ws, '');

    expect(read('AGENTS.md')).toBe('');
    expect(read('CLAUDE.md')).toBe(CLAUDE_POINTER);
    expect(results.every((r) => r.ok)).toBe(true);
  });

  it('marks the generated pointer so a human reading CLAUDE.md is sent to AGENTS.md', () => {
    writeWorkspaceInstructions(ws, BODY);
    expect(read('CLAUDE.md').startsWith(CLAUDE_POINTER_MARKER)).toBe(true);
  });

  it('records the applied text as a sha in the ownership sidecar', () => {
    writeWorkspaceInstructions(ws, BODY);
    expect(read(OWNERSHIP_MARKER).trim()).toMatch(/^[0-9a-f]{64}$/);
  });

  it('reports a failed write per file instead of losing the other result', () => {
    // CLAUDE.md unwritable (a directory). AGENTS.md still lands, and — unlike an exception
    // escaping to the caller's catch — its success is still reported.
    fs.mkdirSync(path.join(ws, 'CLAUDE.md'));

    const results = writeWorkspaceInstructions(ws, BODY);

    expect(read('AGENTS.md')).toBe(BODY);
    const agents = results.find((r) => r.path.endsWith('AGENTS.md'))!;
    const claude = results.find((r) => r.path.endsWith('CLAUDE.md'))!;
    expect(agents.ok).toBe(true);
    expect(claude.ok).toBe(false);
    expect(claude.error).toBeTruthy();
  });

  // The mirror of the case above, and the dangerous direction: if AGENTS.md does NOT land, a
  // pointer in CLAUDE.md imports a file that is absent (or stale), so the workspace is left with
  // no readable instructions at all — worse than the pre-SCRUM-479 behaviour, which put the text
  // in CLAUDE.md and worked. The text has to survive in whichever file we could actually write.
  it('falls back to the full text in CLAUDE.md when AGENTS.md cannot be written', () => {
    fs.mkdirSync(path.join(ws, 'AGENTS.md'));

    const results = writeWorkspaceInstructions(ws, BODY);

    const agents = results.find((r) => r.path.endsWith('AGENTS.md'))!;
    const claude = results.find((r) => r.path.endsWith('CLAUDE.md'))!;
    expect(agents.ok).toBe(false);
    expect(agents.error).toBeTruthy();
    // The instructions are still on disk and still readable by every engine.
    expect(claude.ok).toBe(true);
    expect(read('CLAUDE.md')).toBe(BODY);
    expect(read('CLAUDE.md')).not.toContain('@AGENTS.md');
  });

  // A legacy workspace whose CLAUDE.md holds the real deployed instructions: a failed AGENTS.md
  // write must not replace that last working copy with a dangling import.
  it('does not destroy a legacy CLAUDE.md when the AGENTS.md write fails', () => {
    fs.writeFileSync(path.join(ws, 'CLAUDE.md'), '# Deployed instructions\nStill here.\n');
    fs.mkdirSync(path.join(ws, 'AGENTS.md'));

    writeWorkspaceInstructions(ws, BODY);

    expect(read('CLAUDE.md')).toBe(BODY);
  });

  // Content landed but the sidecar did not: AGENTS.md genuinely holds the text, so CLAUDE.md is
  // still a correct pointer. `ok` stays false because ownership was not recorded — the next apply
  // re-adopts via the byte-equal clause and retries the marker.
  it('keeps CLAUDE.md a pointer when only the ownership marker fails', () => {
    fs.mkdirSync(path.join(ws, OWNERSHIP_MARKER));

    const results = writeWorkspaceInstructions(ws, BODY);

    const agents = results.find((r) => r.path.endsWith('AGENTS.md'))!;
    expect(read('AGENTS.md')).toBe(BODY);
    expect(agents.ok).toBe(false);
    expect(agents.error).toContain('ownership marker failed');
    expect(read('CLAUDE.md')).toBe(CLAUDE_POINTER);
  });
});
